name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          npm ci

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Move build files
        run: |
          rm -rf ./dist
          mkdir -p ./dist
          cp -r frontend/dist/* ./dist/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          clean: true
          domain: ${{ github.repository }}.github.io

      - name: Clean up
        run: |
          rm -rf ./dist
